### Login Vasily
POST http://localhost:8083/login
Content-Type: application/x-www-form-urlencoded

username=vasily@gmail.com&password=vasily

### Login Petro
POST http://localhost:8083/login
Content-Type: application/x-www-form-urlencoded

username=petro@gmail.com&password=petro

### Create new event
POST http://localhost:8083/api/events
Content-Type: application/json

{
  "title": "Party1",
  "description": "bla bla bla",
  "startDateTime": "2024-01-28T18:00:00",
  "endDateTime": "2024-01-28T21:00:00"

}

### Update existing event
PATCH http://localhost:8083/api/events/1
Content-Type: application/json

{
  "title": "Party",
  "description": "bla bla bla :) 3",
  "startDateTime": "2024-01-28T18:00:00",
  "endDateTime": "2024-01-28T21:00:00",
  "userIds": [2]
}

### Logout
POST http://localhost:8083/logout
