### Login Vasily
POST http://localhost:8083/login
Content-Type: application/x-www-form-urlencoded

username=vasily@gmail.com&password=vasily

### Login Petro
POST http://localhost:8083/login
Content-Type: application/x-www-form-urlencoded

username=petro@gmail.com&password=petro

### Create new event
POST http://localhost:8083/api/events
Content-Type: application/json

{
  "title": "Party1",
  "description": "bla bla bla",
  "startDateTime": "2024-01-28T18:00:00",
  "endDateTime": "2024-01-28T21:00:00"

}

### Update existing event
PATCH http://localhost:8083/api/events/2
Content-Type: application/json

{
  "title": "Party",
  "description": "bla bla bla :) 3",
  "startDateTime": "2024-01-28T18:00:00",
  "endDateTime": "2024-01-28T21:00:00",
  "userIds": [2]
}

### Get participationg Events
GET http://localhost:8083/api/events/participating
Content-Type: application/json

### Add permission
POST http://localhost:8083/api/acl
Content-Type: application/json

{
  "objectIdentity": {
    "type": "ua.spro.securityacl.entity.Event",
    "id": 1
  },
  "userId": 2,
  "permission": 2,
  "granting": true
}


### Logout
POST http://localhost:8083/logout
